[package]
name = "tdcparser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psfparser = "0.1.2"
rust_decimal = "1.35.0"
rust_xlsxwriter = "0.64.1"
